version: '3.8'

services:
  db-shipping-app-postgres:
    container_name: db-shipping-app-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5444:5432"
    volumes:
      - db-shipping-app-postgres-volume:/var/lib/postgresql/data
volumes:
  db-shipping-app-postgres-volume:
