version: '3.8'

services:
  frontend-shipping-app:
    build: ../frontend
    depends_on:
      - backend-shipping-app
    ports:
      - "4200:4200"
    networks:
      - network-backend
  backend-shipping-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-shipping-app-postgres
    ports:
      - "3000:3000"
    networks:
      - network-backend
    volumes:
      - ./src:/app/src
  db-shipping-app-postgres:
    container_name: db-shipping-app-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5444:5432"
    networks:
      - network-backend
    volumes:
      - db-shipping-app-postgres-volume:/var/lib/postgresql/data
networks:
  network-backend:
volumes:
  db-shipping-app-postgres-volume:
